/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -p cache_proxy ../../Interfaces/com.scythestudio.cache.xml
 *
 * qdbusxml2cpp is Copyright (C) 2020 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#ifndef CACHE_PROXY_H
#define CACHE_PROXY_H

#include <QtCore/QObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>
#include <QtDBus/QtDBus>

/*
 * Proxy class for interface com.scythestudio.cache
 */
class ComScythestudioCacheInterface: public QDBusAbstractInterface
{
    Q_OBJECT
public:
    static inline const char *staticInterfaceName()
    { return "com.scythestudio.cache"; }

public:
    ComScythestudioCacheInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent = nullptr);

    ~ComScythestudioCacheInterface();

public Q_SLOTS: // METHODS
Q_SIGNALS: // SIGNALS
    void ping(const QString &message);
    void status(const QString &currentStatus);
};

namespace com {
  namespace scythestudio {
    typedef ::ComScythestudioCacheInterface cache;
  }
}
#endif
